export {default as Home} from './pages/Home'
export {default as LandingHero} from './assets/landing_hero_HQ.png'
export {default as c} from './assets/c.svg'
export {default as css} from './assets/css.svg'
export {default as django} from './assets/django.svg'
export {default as git} from './assets/git.svg'
export {default as html} from './assets/html.svg'
export {default as javascript} from './assets/javascript.svg'
export {default as python} from './assets/python.svg'
export {default as react} from './assets/react.svg'
export {default as sql} from './assets/sql.svg'
export {default as tailwind} from './assets/tailwind.svg'
export {default as Layout} from './pages/Layout'
export {default as Projects} from './pages/Projects'
export {default as Certifications} from './pages/Certifications'
export {default as Contact} from './pages/Contact'
export {default as MainProjectsSlides} from './components/MainProjectsSlides'
// export {default as React_img} from './assets/React_image.png'
// export {default as Frontend_mentor_img} from './assets/frontend_mentor_image.png'
// export {default as Django_img} from './assets/django_image.png'
// export {default as Javascript_img} from './assets/javascript_image.jpg'
// export {default as HtmlxCss_img} from './assets/htmlxcss_image.webp'